import React, { useRef, useCallback } from 'react';
import ClayObject from './ClayObject';
import TransformGizmo from './TransformGizmo';
export default function Canvas({ objects, states, selectedId, onSelectObject, onDragObject, onResize, onRotate, background, currentTime, viewport }) {
  const canvasRef = useRef(null); const gizmoSvgRef = useRef(null);
  const handlePointerDown = useCallback((e, objId) => { e.preventDefault(); e.stopPropagation(); onSelectObject(objId); const startX = e.clientX, startY = e.clientY; const state = states[objId]; if (!state) return; const origX = state.x, origY = state.y; const onMove = (mv) => onDragObject(objId, origX + (mv.clientX - startX), origY + (mv.clientY - startY)); const onUp = () => { window.removeEventListener('pointermove', onMove); window.removeEventListener('pointerup', onUp); }; window.addEventListener('pointermove', onMove); window.addEventListener('pointerup', onUp); }, [states, onSelectObject, onDragObject]);
  const selectedState = selectedId ? states[selectedId] : null; const sortedObjects = [...objects].sort((a, b) => ((a.depth || 0) - (b.depth || 0)));
  const safeStyle = viewport ? { width: `min(calc(100% - 48px), ${viewport.width}px)`, aspectRatio: `${viewport.width}/${viewport.height}`, position:'absolute', left:'50%', top:'50%', transform:'translate(-50%, -50%)', border:'1px solid rgba(255,255,255,0.2)', boxShadow:'0 0 0 2000px rgba(0,0,0,0.12) inset', pointerEvents:'none' } : null;
  return <div ref={canvasRef} onClick={(e) => { if (e.target === canvasRef.current) onSelectObject(null); }} style={{ flex:1, position:'relative', background, overflow:'hidden', cursor:'default' }}><div style={{ position:'absolute', inset:0, pointerEvents:'none', backgroundImage:'radial-gradient(circle, rgba(255,255,255,0.05) 1px, transparent 1px)', backgroundSize:'32px 32px' }} /><div style={{ position:'absolute', inset:0, pointerEvents:'none', background:'radial-gradient(ellipse at 50% 50%, rgba(123,97,255,0.07) 0%, transparent 70%)' }} />{safeStyle && <div style={safeStyle}><div style={{ position:'absolute', inset:12, border:'1px dashed rgba(255,255,255,0.14)' }} /></div>}{sortedObjects.map(obj => <ClayObject key={obj.id} obj={obj} state={states[obj.id]} isSelected={selectedId === obj.id} currentTime={currentTime} onPointerDown={(e) => handlePointerDown(e, obj.id)} />)}{selectedId && selectedState && <TransformGizmo state={selectedState} svgRef={gizmoSvgRef} onResize={(w,h) => onResize(selectedId,w,h)} onRotate={(deg) => onRotate(selectedId,deg)} />}<svg ref={gizmoSvgRef} width="100%" height="100%" style={{ position:'absolute', inset:0, pointerEvents:'none' }} /><div style={{ position:'absolute', left:'50%', top:'50%', pointerEvents:'none', transform:'translate(-50%, -50%)', width:16, height:16 }}><div style={{ position:'absolute', left:7, top:0, width:1, height:16, background:'rgba(255,255,255,0.08)' }} /><div style={{ position:'absolute', top:7, left:0, height:1, width:16, background:'rgba(255,255,255,0.08)' }} /></div></div>;
}
