import React from 'react';
import { catmullRomPath, getLimbPoints } from '../engine/modelUtils';
const lighten = (hex, amount) => { if (!hex || !hex.startsWith('#')) return '#fff'; const num = parseInt(hex.replace('#', ''), 16); const r = Math.min(255, Math.max(0, (num >> 16) + Math.round(255 * amount))); const g = Math.min(255, Math.max(0, ((num >> 8) & 0xff) + Math.round(255 * amount))); const b = Math.min(255, Math.max(0, (num & 0xff) + Math.round(255 * amount))); return `rgb(${r},${g},${b})`; };
const darken = (hex, amount) => lighten(hex, -amount);
const getClayFilter = (mode, depth, z = 0) => mode === 'flat2d' ? 'none' : `drop-shadow(0px ${4 + ((depth||0)+(z||0))*1.5}px ${8 + ((depth||0)+(z||0))*2}px rgba(0,0,0,0.5)) drop-shadow(0px -2px 4px rgba(255,255,255,0.12))`;
function SpriteLayer({ state }) {
  const parts = state.spriteParts; if (!parts) return null; const slots = [{ key:'eyes', y: state.height*0.26, w: state.width*0.25, h: state.height*0.1 }, { key:'mouth', y: state.height*0.43, w: state.width*0.2, h: state.height*0.12 }];
  return <>{slots.map(slot => { const part = parts[slot.key]; const frames = part?.tracks?.[0]?.frames || []; const frame = frames.length ? frames[Math.floor(((state._currentTime || 0) / 120) % frames.length)] : null; if (frame) return <img key={slot.key} src={frame.src} alt="" style={{ position:'absolute', left:'50%', top: slot.y, width:slot.w, height:slot.h, transform:'translate(-50%, -50%)', pointerEvents:'none', objectFit:'contain' }} />; if (slot.key === 'eyes') return <div key={slot.key} style={{ position:'absolute', left:'50%', top: slot.y, transform:'translate(-50%, -50%)', display:'flex', gap: state.width*0.08 }}><div style={{ width: state.width*0.04, height: state.height*0.04, background:'#101022', borderRadius:'50%' }} /><div style={{ width: state.width*0.04, height: state.height*0.04, background:'#101022', borderRadius:'50%' }} /></div>; return <div key={slot.key} style={{ position:'absolute', left:'50%', top: slot.y, width:state.width*0.12, height:state.height*0.035, borderRadius:20, background:'#8c4059', transform:'translate(-50%, -50%)' }} />; })}</>;
}
function CustomModelShape({ obj, state, isSelected, currentTime }) {
  const { width, height, rotation, scaleX, scaleY, rotateX, rotateY, mode, opacity } = state; const layers = [...(state.layers || obj.layers || [])].sort((a,b)=>(a.z||0)-(b.z||0));
  const allPts = layers.flatMap(l => l.points || []); if (!allPts.length) return null;
  const minX = Math.min(...allPts.map(p => p.x)), maxX = Math.max(...allPts.map(p => p.x)), minY = Math.min(...allPts.map(p => p.y)), maxY = Math.max(...allPts.map(p => p.y));
  const srcW = (maxX - minX) || 1, srcH = (maxY - minY) || 1; const isClay = mode === 'clay3d';
  const transform3d = isClay ? `perspective(600px) rotateX(${rotateX||0}deg) rotateY(${rotateY||0}deg) rotate(${rotation||0}deg) scaleX(${scaleX||1}) scaleY(${scaleY||1})` : `rotate(${rotation||0}deg) scaleX(${scaleX||1}) scaleY(${scaleY||1})`;
  return <div style={{ position:'absolute', width, height, left:'50%', top:'50%', marginLeft:-width/2, marginTop:-height/2, opacity, transform:transform3d, transformOrigin:'center', outline:isSelected?'2px solid rgba(255,255,255,0.7)':'none', outlineOffset:3 }}><svg width={width} height={height} viewBox={`${minX} ${minY} ${srcW} ${srcH}`} style={{ overflow:'visible', display:'block' }}><defs>{layers.map(layer => <radialGradient key={layer.id} id={`cg-${obj.id}-${layer.id}`} cx="35%" cy="30%" r="65%"><stop offset="0%" stopColor={lighten(layer.color, 0.55)} /><stop offset="45%" stopColor={layer.color} /><stop offset="100%" stopColor={darken(layer.color, 0.35)} /></radialGradient>)}</defs>{layers.map(layer => { let pts = getLimbPoints(layer, currentTime||0); if (obj.walkCycle?.enabled && (layer.id.includes('leg') || layer.id.includes('arm'))) { const walk = Math.sin((currentTime || 0) / 120 * (obj.walkCycle.speed || 1)); pts = pts.map((p, i) => ({ ...p, y: p.y + (i % 2 === 0 ? walk * 2 : -walk * 2), x: p.x + (layer.id.includes('leg') ? walk * (layer.id.includes('l') ? -1.5 : 1.5) : walk * (layer.id.includes('l') ? 1.2 : -1.2)) })); }
    const path = catmullRomPath(pts, true); if (!path) return null; return <g key={layer.id}><path d={path} fill={isClay ? `url(#cg-${obj.id}-${layer.id})` : layer.color} stroke={lighten(layer.color, 0.1)} strokeWidth={isClay ? 1 : 0.5} style={{ filter: isClay ? `drop-shadow(0 3px 6px rgba(0,0,0,0.4))` : 'none' }} /></g>; })}</svg><SpriteLayer state={state} /></div>;
}
const ClayShape = ({ obj, state, isSelected }) => {
  if (obj.type === 'custom' || (obj.layers && obj.layers.length > 0)) return <CustomModelShape obj={obj} state={state} isSelected={isSelected} currentTime={state._currentTime} />;
  const { mode, rotateX, rotateY, rotation, scaleX, scaleY, width, height, borderRadius, opacity, depth, z, materialTexture } = state; const isClay = mode === 'clay3d'; const color = state.color; const effectiveDepth = (depth || 0) + (z || 0);
  const transform3d = isClay ? `perspective(600px) rotateX(${rotateX || 0}deg) rotateY(${rotateY || 0}deg) rotate(${rotation || 0}deg) scaleX(${scaleX || 1}) scaleY(${scaleY || 1})` : `rotate(${rotation || 0}deg) scaleX(${scaleX || 1}) scaleY(${scaleY || 1})`;
  const clayStyle = isClay ? { background: materialTexture ? `url(${materialTexture})` : state.secondColor ? `radial-gradient(circle at 30% 30%, ${lighten(color, 0.4)} 0%, ${color} 45%, ${darken(color, 0.3)} 100%)` : color, backgroundSize: materialTexture ? 'cover' : undefined, backgroundPosition: materialTexture ? 'center' : undefined, boxShadow: `inset -${Math.round(width * 0.08)}px -${Math.round(height * 0.08)}px ${Math.round(width * 0.15)}px rgba(0,0,0,0.35), inset ${Math.round(width * 0.04)}px ${Math.round(height * 0.04)}px ${Math.round(width * 0.1)}px rgba(255,255,255,0.25), 0 ${8 + effectiveDepth * 2}px ${16 + effectiveDepth * 4}px rgba(0,0,0,0.4)` } : { background: materialTexture ? `url(${materialTexture})` : state.secondColor ? `linear-gradient(${state.gradientAngle || 135}deg, ${color}, ${state.secondColor})` : color, backgroundSize: materialTexture ? 'cover' : undefined, backgroundPosition: materialTexture ? 'center' : undefined, boxShadow: `0 ${4 + effectiveDepth * 2}px 20px rgba(0,0,0,0.3)` };
  const base = { position:'absolute', width, height, left:'50%', top:'50%', marginLeft:-width/2, marginTop:-height/2, borderRadius, opacity, transform:transform3d, transformOrigin:'center', transition:'none', willChange:'transform', outline:isSelected ? '2px solid rgba(255,255,255,0.8)' : 'none', outlineOffset:3, ...clayStyle };
  if (obj.type === 'star') return <div style={{ ...base, background:'transparent', boxShadow:'none', display:'flex', alignItems:'center', justifyContent:'center' }}><svg width={width} height={height} viewBox="0 0 100 100"><polygon points="50,5 61,35 95,35 68,57 79,91 50,70 21,91 32,57 5,35 39,35" fill={color} /></svg></div>;
  if (obj.type === 'diamond') return <div style={{ ...base, background:'transparent', boxShadow:'none', display:'flex', alignItems:'center', justifyContent:'center' }}><svg width={width} height={height} viewBox="0 0 100 100"><polygon points="50,5 95,50 50,95 5,50" fill={color} /></svg></div>;
  if (obj.type === 'ring') return <div style={{ ...base, background:'transparent', boxShadow:'none', display:'flex', alignItems:'center', justifyContent:'center' }}><svg width={width} height={height} viewBox="0 0 100 100"><circle cx="50" cy="50" r="40" fill="none" stroke={color} strokeWidth={isClay ? 18 : 12} /></svg></div>;
  if (obj.type === 'text') return <div style={{ ...base, background:'transparent', boxShadow:'none', display:'flex', alignItems:'center', justifyContent:'center' }}><span style={{ color, fontSize:Math.round(height*0.6), fontWeight:800 }}>{obj.text}</span></div>;
  if (obj.type === 'button' || obj.type === 'badge') return <div style={{ ...base, display:'flex', alignItems:'center', justifyContent:'center' }}><span style={{ color:'#fff', fontSize:Math.round(height*0.38), fontWeight:700 }}>{obj.text || (obj.type === 'badge' ? 'NEW' : 'Click Me')}</span></div>;
  if (obj.type === 'card') return <div style={{ ...base, background:'rgba(20,26,60,0.8)', backdropFilter:'blur(20px)', border:'1px solid rgba(255,255,255,0.12)', boxShadow:`0 20px 60px rgba(0,0,0,0.5)` }} />;
  return <div style={base} />;
};
export default function ClayObject({ obj, state, isSelected, onPointerDown, currentTime }) {
  if (!state || state.opacity <= 0) return null; const enrichedState = currentTime !== undefined ? { ...state, _currentTime: currentTime } : state;
  return <div style={{ position:'absolute', left:state.x, top:state.y, zIndex:(state.depth ?? 0)+10, cursor:'grab', transform:'translate(-50%, -50%)', filter:getClayFilter(state.mode, state.depth ?? 0, state.z ?? 0) }} onPointerDown={onPointerDown}><ClayShape obj={obj} state={enrichedState} isSelected={isSelected} /></div>;
}
