import React from 'react';
const H = 9; const ROT_LINE = 32;
const HANDLE_SIGNS = { tl:{sx:-1,sy:-1}, tc:{sx:0,sy:-1}, tr:{sx:1,sy:-1}, ml:{sx:-1,sy:0}, mr:{sx:1,sy:0}, bl:{sx:-1,sy:1}, bc:{sx:0,sy:1}, br:{sx:1,sy:1} };
const HANDLE_CURSORS = { tl:'nwse-resize', tc:'ns-resize', tr:'nesw-resize', ml:'ew-resize', mr:'ew-resize', bl:'nesw-resize', bc:'ns-resize', br:'nwse-resize' };
export default function TransformGizmo({ state, svgRef, onResize, onRotate }) {
  if (!state || state.opacity <= 0 || !state.width || !state.height) return null;
  const { x, y, width, height, rotation = 0 } = state; const hw = width / 2, hh = height / 2; const rot = rotation * Math.PI / 180; const cos = Math.cos(rot), sin = Math.sin(rot);
  const toCanvas = (lx, ly) => ({ x: x + lx * cos - ly * sin, y: y + lx * sin + ly * cos });
  const corners = [toCanvas(-hw, -hh), toCanvas(hw, -hh), toCanvas(hw, hh), toCanvas(-hw, hh)];
  const handles = Object.entries(HANDLE_SIGNS).map(([id, { sx, sy }]) => ({ id, ...toCanvas(sx * hw, sy * hh) }));
  const rotLineEnd = toCanvas(0, -hh); const rotPt = toCanvas(0, -hh - ROT_LINE);
  const startResize = (e, handleId) => { e.preventDefault(); e.stopPropagation(); const startX = e.clientX, startY = e.clientY; const origW = width, origH = height; const { sx, sy } = HANDLE_SIGNS[handleId]; const move = (mv) => { const dx = mv.clientX - startX, dy = mv.clientY - startY; const localDx = dx * cos + dy * sin; const localDy = -dx * sin + dy * cos; onResize(sx !== 0 ? Math.max(8, origW + 2 * sx * localDx) : origW, sy !== 0 ? Math.max(8, origH + 2 * sy * localDy) : origH); }; const up = () => { window.removeEventListener('pointermove', move); window.removeEventListener('pointerup', up); }; window.addEventListener('pointermove', move); window.addEventListener('pointerup', up); };
  const startRotate = (e) => { e.preventDefault(); e.stopPropagation(); const svgRect = svgRef.current?.getBoundingClientRect(); if (!svgRect) return; const move = (mv) => { const mx = mv.clientX - svgRect.left, my = mv.clientY - svgRect.top; const angle = Math.atan2(my - y, mx - x) * 180 / Math.PI + 90; onRotate(angle); }; const up = () => { window.removeEventListener('pointermove', move); window.removeEventListener('pointerup', up); }; window.addEventListener('pointermove', move); window.addEventListener('pointerup', up); };
  return <svg ref={svgRef} width="100%" height="100%" style={{ position: 'absolute', inset: 0, pointerEvents: 'none', overflow: 'visible', zIndex: 50, top: 0, left: 0 }}><polygon points={corners.map(p => `${p.x},${p.y}`).join(' ')} fill="none" stroke="rgba(255,255,255,0.75)" strokeWidth="1.5" strokeDasharray="5 3" /><line x1={rotLineEnd.x} y1={rotLineEnd.y} x2={rotPt.x} y2={rotPt.y} stroke="rgba(123,97,255,0.6)" strokeWidth="1" />{handles.map(h => <rect key={h.id} x={h.x - H / 2} y={h.y - H / 2} width={H} height={H} rx="2" fill="white" stroke="rgba(0,0,0,0.35)" strokeWidth="1.5" style={{ pointerEvents: 'all', cursor: HANDLE_CURSORS[h.id] }} onPointerDown={e => startResize(e, h.id)} />)}<circle cx={rotPt.x} cy={rotPt.y} r={7} fill="#7B61FF" stroke="white" strokeWidth="2" style={{ pointerEvents: 'all', cursor: 'crosshair' }} onPointerDown={startRotate} /><text x={rotPt.x} y={rotPt.y + 1} textAnchor="middle" dominantBaseline="middle" fontSize="8" fill="white" style={{ pointerEvents: 'none', userSelect: 'none' }}>↻</text></svg>;
}
